spring:
  application:
    name: msd

server:
  port: 0

# Definindo onde o servico vai se conectar.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  # Gerando uma porta randomica.
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}